<div class="bodyContent single">
	<div class="contentSubMenu">
		<a title="Edit Gallery Settings" class="selected" href="index.php?c=config">画廊设置</a>
		<a title="Edit Email Templates"  href="index.php?c=config&amp;a=templates">邮件模版</a>
		<a title="Edit Custom CSS" href="index.php?c=config&amp;a=css">自定义样式</a>

	</div>
	<?php if (!in_array('noteSettings', ivPool::get('notes'))): ?>
		<div class="note">
			<a id="noteSettings" href="#" class="close">&times;</a>
			设置页允许你更改你的画廊怎样工作
			<a title="About Imagevue Settings" href="http://imagevuex.com/documentation/settings-page/" target="_blank" class="iv-ext">设置页</a>
		</div>
	<?php endif; ?>

	<form method="post" action="">

		<div class="controls left">
			<input type="submit" class="button buttonSave" name="save" value="保存" />
			<input type="button" class="button buttonExpand" value="全部展开" onclick="$('.ivconf').each(function () {$(this).addClass('open').next().show();});" />
			<input type="button" class="button buttonCollapse" value="全部折叠" onclick="$('.ivconf').each(function () {$(this).removeClass('open').next().hide();});" />
		</div>

		<div class="contentMenu" id="configTabHeaders">
			<?php $sections = $this->sections; ?>
			<?php foreach ($sections as $name => $flatSection): ?>
				<a href="#<?php echo htmlspecialchars($name); ?>" class="tabHeader config-<?php echo htmlspecialchars($name); ?>"><?php echo htmlspecialchars(ucfirst($name)); ?></a>
			<?php endforeach; ?>
		</div>
		<?php echo $this->partial('formtree', array('sections' => $this->sections, 'openedPanels' => $this->openedPanels)); ?>
	</div>

		<div class="controls left">
			<input type="submit" class="button buttonSave" name="save" value="保存" />
			<input type="button" class="button buttonExpand" value="全部展开" onclick="$('.ivconf').each(function () {$(this).addClass('open').next().show();});" />
			<input type="button" class="button buttonCollapse" value="全部折叠" onclick="$('.ivconf').each(function () {$(this).removeClass('open').next().hide();});" />
		</div>
	</form>
</div>